export enum EPermissionsSkyledger {
  VER_PROCESO = 'SKYLEDER:VER_PROCESO',
  VER_ARCHIVOS = 'SKYLEDER:VER_ARCHIVOS',
  APROBAR_ARCHIVOS = 'SKYLEDER:APROBAR_ARCHIVOS',
}

export enum EPermissionsTiposDeCambio {
  VER_PROCESO = 'TIPOS_DE_CAMBIO:VER_PROCESO',
  VER_ARCHIVOS = 'TIPOS_DE_CAMBIO:VER_ARCHIVOS',
}

export enum EPermissionsDatosMaestros {
  VER_PROVEEDORES = 'DATOS_MAESTROS:VER_PROVEEDORES',
  APROBAR_MAIL_PROVEEDOR = 'DATOS_MAESTROS:APROBAR_MAIL_PROVEEDOR',
  APROBAR_PROVEEDOR = 'DATOS_MAESTROS:APROBAR_PROVEEDOR',
  EDITAR_PROVEEDOR = 'DATOS_MAESTROS:EDITAR_PROVEEDORES',
  INACTIVAR_PROVEEDOR = 'DATOS_MAESTROS:INACTIVAR_PROVEEDOR',
}

export enum EPermissionsAutorizacionFacturasMiscelaneas {
  VER_PROCESO = 'AUTORIZACION_FACTURAS_MISCELANEAS:VER_PROCESO',
  CREAR = 'AUTORIZACION_FACTURAS_MISCELANEAS:CREAR',
  APROBAR_CARGA = 'AUTORIZACION_FACTURAS_MISCELANEAS:APROBAR_CARGA',
  APROBAR_HANDLER = 'AUTORIZACION_FACTURAS_MISCELANEAS:APROBAR_HANDLER',
}

export enum EPermissionsPayroll {
  VER_PROCESO = 'PAYROLL:VER_PROCESO',
  CARGAR_ARCHIVO = 'PAYROLL:CARGAR_ARCHIVO',
  APROBAR_ARCHIVOS = 'PAYROLL:APROBAR_ARCHIVOS',
  VER_MIS_PROCESOS = 'PAYROLL:VER_MIS_PROCESOS',
}

export enum EPermissionsRecepcionFacturasClientesCredito {
  VER_PROCESO = 'RECEPCION_FACTURAS_CLIENTES_CREDITO:VER_PROCESO',
}

export enum EPermissionsGeneracionFacturasMiscelaneas {
  VER_PROCESO = 'GENERACION_FACTURAS_MISCELANEAS:VER_PROCESO',
}

export enum EPermissionsAmos {
  VER_PROCESO = 'AMOS:VER_PROCESO',
}

export enum EPermissionsUsers {
  USUARIO_VER = 'USUARIOS:VER',
  ROL_ASIGNAR = 'ROLES:ASIGNAR',
}

export enum EPermissionsRoles {
  ROL_VER = 'ROL:VER',
  ROL_MODIFICAR = 'ROL:MODIFICAR',
  ROL_INACTIVA = 'ROL:INACTIVA',
  ROL_CREAR = 'ROL:CREAR',
}
